name: ci
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    name: test
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [stable, macos, win-msvc]
        include:
        - build: stable
          os: ubuntu-latest
          rust: stable
        - build: macos
          os: macos-latest
          rust: stable
        - build: win-msvc
          os: windows-latest
          rust: stable
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      run: |
        rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - name: Build neptungen and all crates
      run: |
        cargo build --verbose --all
    - name: Check formatting
      run: |
        cargo fmt --all -- --check
    - name: Clippy checks
      run: |
        cargo clippy

